spring.application.name=zanchi-backend

# ===== DB (MariaDB) =====
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/zanchi_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ===== File Upload Path =====
app.upload.dir=${user.home}/fitlog/uploads/clips
app.upload.root=${user.home}/fitlog/uploads
app.upload.avatar-dir=${user.home}/fitlog/uploads/avatars
spring.servlet.multipart.location=${user.home}/fitlog/tmp

# ===== File Size Limit =====
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ===== JWT =====
# ????? ????(-Djwt.secret=... ?? .env)? ?? ??
jwt.secret=PASTE_BASE64_SECRET_HERE

# ===== Redis =====
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=YOUR_REDIS_PASSWORD

# ===== Dev ??: Redis ?? ??? =====
auth.dev.ignore-redis=true

# ===== Spring AI ?? ?? =====
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.2
spring.ai.retry.enabled=false
# spring.ai.retry.max-attempts=3
# spring.ai.retry.backoff.initial-interval=500ms

# ===== ?? API Host =====
app.maps.kakao.host=https://dapi.kakao.com

# ===== Server =====
server.port=8080
server.forward-headers-strategy=framework

# ===== Logging =====
logging.level.com.zanchi.zanchi_backend.config.jwt=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.springframework.ai=INFO
logging.level.org.springframework.web.client=INFO
logging.level.org.springframework.security=INFO
logging.level.com.zanchi.zanchi_backend=INFO

# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.ai.openai.api-key=${OPENAI_API_KEY}
app.maps.google.api-key=${GOOGLE_MAPS_API_KEY}
app.maps.kakao.rest-api-key=${KAKAO_REST_API_KEY}

# ?? ???(???)
app.cors.allowed-origins=https://zanchi-frontend.vercel.app,https://zanchi-frontend-w3bh.vercel.app,http://localhost:3000

aws.region=ap-northeast-2
aws.personalize.campaign-arn=${AWS_PERSONALIZE_CAMPAIGN_ARN:}

# S3 ?? ??
app.s3.bucket=${S3_BUCKET:}

# Personalize
reco.personalize.campaign-arn=${PERSONALIZE_CAMPAIGN_ARN:${AWS_PERSONALIZE_CAMPAIGN_ARN:}}
